services:
  chestxray:
    build: .
    container_name: pbn-chestxray-v7

    volumes:
      - ./src:/app/src
      # - ${ARCHIVE_HOST_PATH}:/app/archive
      - D:/senior-project/ploy-senior-project/archive:/archive
      - ./outputs:/app/outputs
      - ./models_v7:/app/models_v7

    command: python src/train_V7.py

    depends_on:
      - pushgateway

    networks:
      - chestxray-network


  pushgateway:
    image: prom/pushgateway:latest
    container_name: pbn-pushgateway

    ports:
      - "9091:9091"

    networks:
      - chestxray-network


  prometheus:
    image: prom/prometheus:latest
    container_name: pbn-prometheus

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

    ports:
      - "9090:9090"

    depends_on:
      - pushgateway

    networks:
      - chestxray-network


  grafana:
    image: grafana/grafana:latest
    container_name: pbn-grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

    networks:
      - chestxray-network
  
  telegram-bot:
    build: .
    container_name: pbn-telegram-bot

    command: python -u src/telegram_bot.py

    env_file:
      - .env

    depends_on:
      - prometheus

    networks:
      - chestxray-network


networks:
  chestxray-network:
    name: pbn-chestxray-network