services:
  chestxray:
    build: .
    container_name: pbn-chestxray-v7

    volumes:
      - ./src:/app/src
      - ${ARCHIVE_HOST_PATH}:/app/archive
      - ./outputs:/app/outputs
      - ./models_v7:/app/models_v7

    command: python src/train_V7.py

    networks:
      - chestxray-network

networks:
  chestxray-network:
    name: pbn-chestxray-network
